"""SQL issued by the Snowflake System API.

Every statement lives here, parameterised, and nowhere else.  Two reasons:

  1. Injection.  Customer ids arrive from an HTTP path segment.  The only safe
     answer is bind parameters, and the only way to guarantee bind parameters
     are used is to have one module that builds statements.
  2. Reviewability.  A data platform's real API surface is its query set.  Being
     able to read all of it on one screen makes a security or cost
     review possible.

The statements select from views, never from base tables - see
``snowflake/03-views/02-consumption-views.sql`` for why.
"""
from __future__ import annotations

CUSTOMER_360 = """
SELECT *
FROM ACME_EDP.ANALYTICS.V_CUSTOMER_360_API
WHERE CUSTOMER_ID = ?
"""

CUSTOMER_ORDERS = """
SELECT ORDER_ID, ORDER_DATE, ORDER_STATUS, CHANNEL, CURRENCY_CODE, ORDER_AMOUNT,
       DISCOUNT_AMOUNT, SHIPPING_AMOUNT, NET_AMOUNT, LINE_COUNT, TOTAL_UNITS
FROM ACME_EDP.ANALYTICS.V_CUSTOMER_ORDERS_API
WHERE CUSTOMER_ID = ?
ORDER BY ORDER_DATE DESC
LIMIT ? OFFSET ?
"""

CUSTOMER_ORDER_COUNT = """
SELECT COUNT(*) AS TOTAL
FROM ACME_EDP.ANALYTICS.V_CUSTOMER_ORDERS_API
WHERE CUSTOMER_ID = ?
"""

CUSTOMER_CASES = """
SELECT CASE_ID, CASE_TYPE, PRIORITY, SUBJECT, STATUS, CHANNEL, OPENED_AT, RESOLVED_AT,
       RESOLUTION_HOURS, CSAT_SCORE, REOPEN_COUNT, IS_SLA_BREACHED
FROM ACME_EDP.ANALYTICS.V_CUSTOMER_CASES_API
WHERE CUSTOMER_ID = ?
ORDER BY OPENED_AT DESC
LIMIT ?
"""

CHURN_RISK = """
SELECT CUSTOMER_BK AS CUSTOMER_ID, SCORE_DATE, CHURN_PROBABILITY, CHURN_RISK_BAND,
       MODEL_NAME, MODEL_VERSION, SCORING_METHOD, FEATURE_SET_VERSION,
       TOP_DRIVER_1, TOP_DRIVER_1_CONTRIB, TOP_DRIVER_2, TOP_DRIVER_2_CONTRIB,
       TOP_DRIVER_3, TOP_DRIVER_3_CONTRIB
FROM ACME_EDP.AI.CUSTOMER_CHURN_SCORE
WHERE CUSTOMER_BK = ?
ORDER BY SCORE_DATE DESC
LIMIT 1
"""

CUSTOMER_FEATURES = """
SELECT *
FROM ACME_EDP.AI.CUSTOMER_FEATURES
WHERE CUSTOMER_BK = ?
ORDER BY FEATURE_DATE DESC
LIMIT 1
"""

HIGH_RISK_COHORT = """
SELECT s.CUSTOMER_BK AS CUSTOMER_ID, s.CHURN_PROBABILITY, s.CHURN_RISK_BAND,
       c.VALUE_TIER, c.CUSTOMER_LIFETIME_VALUE, c.DAYS_SINCE_LAST_ORDER, c.LOYALTY_TIER
FROM ACME_EDP.AI.CUSTOMER_CHURN_SCORE s
JOIN ACME_EDP.ANALYTICS.CUSTOMER_360 c ON c.CUSTOMER_BK = s.CUSTOMER_BK
WHERE s.CHURN_RISK_BAND IN ('HIGH', 'CRITICAL')
  AND s.SCORE_DATE = (SELECT MAX(SCORE_DATE) FROM ACME_EDP.AI.CUSTOMER_CHURN_SCORE)
ORDER BY c.CUSTOMER_LIFETIME_VALUE DESC
LIMIT ?
"""

DQ_SCORECARD = """
SELECT RULE_ID, RULE_NAME, DIMENSION, SEVERITY, TARGET_TABLE, ROWS_EVALUATED,
       ROWS_FAILED, FAIL_PCT, STATUS, EXECUTED_AT
FROM ACME_EDP.GOVERNANCE.V_DQ_LATEST
ORDER BY CASE STATUS WHEN 'FAIL' THEN 0 WHEN 'WARN' THEN 1 ELSE 2 END, RULE_ID
"""

PLATFORM_FRESHNESS = """
SELECT MAX(AS_OF_TIMESTAMP) AS CUSTOMER_360_AS_OF,
       COUNT(*)             AS CUSTOMER_COUNT
FROM ACME_EDP.ANALYTICS.CUSTOMER_360
"""
