-- =============================================================================
-- 06-03  RAW -> STAGING : SUPPORT CASES, INTERACTIONS, LOYALTY      [portable]
-- =============================================================================

DELETE FROM ACME_EDP.STAGING.STG_SUPPORT_CASE;

INSERT INTO ACME_EDP.STAGING.STG_SUPPORT_CASE (
    CASE_BK, CUSTOMER_BK, CASE_TYPE, PRIORITY, SUBJECT, DESCRIPTION, STATUS, CHANNEL,
    OPENED_AT, RESOLVED_AT, RESOLUTION_HOURS, RESOLUTION_NOTES, CSAT_SCORE, REOPEN_COUNT,
    DQ_STATUS, _BATCH_ID, _LOADED_AT
)
WITH typed AS (
    SELECT
        TRIM(CASE_ID)                              AS CASE_BK,
        TRIM(CUSTOMER_ID)                          AS CUSTOMER_BK,
        UPPER(TRIM(CASE_TYPE))                     AS CASE_TYPE,
        UPPER(TRIM(PRIORITY))                      AS PRIORITY,
        TRIM(SUBJECT)                              AS SUBJECT,
        TRIM(DESCRIPTION)                          AS DESCRIPTION,
        UPPER(TRIM(STATUS))                        AS STATUS,
        UPPER(TRIM(CHANNEL))                       AS CHANNEL,
        TRY_CAST(OPENED_AT AS TIMESTAMP_NTZ)       AS OPENED_AT,
        TRY_CAST(RESOLVED_AT AS TIMESTAMP_NTZ)     AS RESOLVED_AT,
        TRIM(RESOLUTION_NOTES)                     AS RESOLUTION_NOTES,
        TRY_CAST(CSAT_SCORE AS NUMBER(3,0))        AS CSAT_SCORE,
        COALESCE(TRY_CAST(REOPEN_COUNT AS NUMBER(5,0)), 0) AS REOPEN_COUNT,
        _BATCH_ID
    FROM ACME_EDP.RAW.RAW_SUP_CASE
)
SELECT
    CASE_BK, CUSTOMER_BK, CASE_TYPE, PRIORITY, SUBJECT, DESCRIPTION, STATUS, CHANNEL,
    OPENED_AT, RESOLVED_AT,
    CASE WHEN RESOLVED_AT IS NOT NULL AND OPENED_AT IS NOT NULL
         THEN ROUND(DATEDIFF(second, OPENED_AT, RESOLVED_AT) / 3600.0, 2) END AS RESOLUTION_HOURS,
    RESOLUTION_NOTES, CSAT_SCORE, REOPEN_COUNT,
    CASE
        WHEN CASE_BK IS NULL THEN 'FAIL'                                         -- DQ-S-001
        -- DQ-S-002 chronology: a case cannot be resolved before it was opened
        WHEN RESOLVED_AT IS NOT NULL AND OPENED_AT IS NOT NULL
             AND RESOLVED_AT < OPENED_AT THEN 'FAIL'
        -- DQ-S-003 range: CSAT is a 1-5 scale
        WHEN CSAT_SCORE IS NOT NULL AND (CSAT_SCORE < 1 OR CSAT_SCORE > 5) THEN 'WARN'
        ELSE 'PASS'
    END AS DQ_STATUS,
    _BATCH_ID, CURRENT_TIMESTAMP
FROM typed
WHERE CASE_BK IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY CASE_BK ORDER BY OPENED_AT DESC NULLS LAST) = 1;

-- --------------------------------------------------------------- interactions
DELETE FROM ACME_EDP.STAGING.STG_CUSTOMER_INTERACTION;

INSERT INTO ACME_EDP.STAGING.STG_CUSTOMER_INTERACTION (
    INTERACTION_BK, CUSTOMER_BK, INTERACTION_TYPE, CHANNEL, INTERACTION_TS,
    CAMPAIGN_ID, DQ_STATUS, _BATCH_ID, _LOADED_AT
)
SELECT
    TRIM(INTERACTION_ID), TRIM(CUSTOMER_ID), UPPER(TRIM(INTERACTION_TYPE)),
    UPPER(TRIM(CHANNEL)), TRY_CAST(INTERACTION_TS AS TIMESTAMP_NTZ), TRIM(CAMPAIGN_ID),
    CASE WHEN TRY_CAST(INTERACTION_TS AS TIMESTAMP_NTZ) IS NULL THEN 'WARN' ELSE 'PASS' END,
    _BATCH_ID, CURRENT_TIMESTAMP
FROM ACME_EDP.RAW.RAW_CRM_INTERACTION
WHERE INTERACTION_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY INTERACTION_ID ORDER BY INTERACTION_TS DESC NULLS LAST) = 1;

-- -------------------------------------------------------------------- loyalty
DELETE FROM ACME_EDP.STAGING.STG_LOYALTY_ACCOUNT;

INSERT INTO ACME_EDP.STAGING.STG_LOYALTY_ACCOUNT (
    LOYALTY_ACCOUNT_BK, CUSTOMER_BK, TIER, POINTS_BALANCE, POINTS_EARNED_LIFETIME,
    POINTS_REDEEMED_LIFETIME, ENROLLED_AT, LAST_ACTIVITY_AT, STATUS, DQ_STATUS,
    _BATCH_ID, _LOADED_AT
)
SELECT
    TRIM(LOYALTY_ACCOUNT_ID), TRIM(CUSTOMER_ID), UPPER(TRIM(TIER)),
    TRY_CAST(POINTS_BALANCE AS NUMBER(18,0)),
    TRY_CAST(POINTS_EARNED_LIFETIME AS NUMBER(18,0)),
    TRY_CAST(POINTS_REDEEMED_LIFETIME AS NUMBER(18,0)),
    TRY_CAST(ENROLLED_AT AS DATE), TRY_CAST(LAST_ACTIVITY_AT AS DATE),
    UPPER(TRIM(STATUS)),
    CASE
        WHEN LOYALTY_ACCOUNT_ID IS NULL THEN 'FAIL'
        WHEN UPPER(TRIM(TIER)) NOT IN ('BRONZE','SILVER','GOLD','PLATINUM') THEN 'WARN'
        -- DQ-L-003 consistency: redeemed points cannot exceed points ever earned
        WHEN COALESCE(TRY_CAST(POINTS_REDEEMED_LIFETIME AS NUMBER(18,0)),0)
             > COALESCE(TRY_CAST(POINTS_EARNED_LIFETIME AS NUMBER(18,0)),0) THEN 'WARN'
        ELSE 'PASS'
    END,
    _BATCH_ID, CURRENT_TIMESTAMP
FROM ACME_EDP.RAW.RAW_LOY_ACCOUNT
WHERE LOYALTY_ACCOUNT_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY LOYALTY_ACCOUNT_ID ORDER BY LAST_ACTIVITY_AT DESC NULLS LAST) = 1;

-- ------------------------------------------------------- addresses / contacts
DELETE FROM ACME_EDP.STAGING.STG_CUSTOMER_ADDRESS;

INSERT INTO ACME_EDP.STAGING.STG_CUSTOMER_ADDRESS (
    ADDRESS_BK, CUSTOMER_BK, ADDRESS_TYPE, LINE1, LINE2, CITY, STATE, POSTAL_CODE,
    COUNTRY, IS_PRIMARY, VALID_FROM, DQ_STATUS, _BATCH_ID, _LOADED_AT
)
SELECT
    TRIM(ADDRESS_ID), TRIM(CUSTOMER_ID), UPPER(TRIM(ADDRESS_TYPE)), TRIM(LINE1), TRIM(LINE2),
    TRIM(CITY), UPPER(TRIM(STATE)), TRIM(POSTAL_CODE), UPPER(COALESCE(COUNTRY,'US')),
    CASE WHEN LOWER(IS_PRIMARY) IN ('true','1','y','yes') THEN TRUE ELSE FALSE END,
    TRY_CAST(VALID_FROM AS DATE),
    CASE WHEN POSTAL_CODE IS NULL OR TRIM(POSTAL_CODE) = '' THEN 'WARN' ELSE 'PASS' END,
    _BATCH_ID, CURRENT_TIMESTAMP
FROM ACME_EDP.RAW.RAW_CRM_CUSTOMER_ADDRESS
WHERE ADDRESS_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY ADDRESS_ID ORDER BY VALID_FROM DESC NULLS LAST) = 1;

DELETE FROM ACME_EDP.STAGING.STG_CUSTOMER_CONTACT;

INSERT INTO ACME_EDP.STAGING.STG_CUSTOMER_CONTACT (
    CONTACT_BK, CUSTOMER_BK, CONTACT_TYPE, CONTACT_VALUE, IS_VERIFIED, IS_PRIMARY,
    DQ_STATUS, _BATCH_ID, _LOADED_AT
)
SELECT
    TRIM(CONTACT_ID), TRIM(CUSTOMER_ID), UPPER(TRIM(CONTACT_TYPE)), TRIM(CONTACT_VALUE),
    CASE WHEN LOWER(IS_VERIFIED) IN ('true','1','y','yes') THEN TRUE ELSE FALSE END,
    CASE WHEN LOWER(IS_PRIMARY)  IN ('true','1','y','yes') THEN TRUE ELSE FALSE END,
    'PASS', _BATCH_ID, CURRENT_TIMESTAMP
FROM ACME_EDP.RAW.RAW_CRM_CUSTOMER_CONTACT
WHERE CONTACT_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY CONTACT_ID ORDER BY CONTACT_TYPE) = 1;
