#!/usr/bin/env python3
"""Generate docs/data-dictionary.md from the warehouse.

Generated instead of hand-written, so it cannot drift from the schema. The
business definitions and ownership come from GOVERNANCE.DATA_DICTIONARY (which
*is* hand-curated, because a machine cannot write a business definition); the
structure comes from the information schema.

Run: python scripts/generate_data_dictionary.py   (or `make docs`)
"""
from __future__ import annotations

import sys
from datetime import UTC, datetime
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(REPO), str(REPO / "services")]

LAYER_NOTES = {
    "RAW": "Immutable landing. Permissive types so a source-side change cannot break "
           "ingestion. Never queried by a consumer.",
    "STAGING": "Typed, cleansed, deduplicated. Disposable - rebuildable from RAW at any time.",
    "CORE": "Conformed enterprise entities. The system of record for analytics. "
            "`CUSTOMER` is the only Type 2 dimension.",
    "ANALYTICS": "Consumption-shaped models, including `CUSTOMER_360`.",
    "AI": "Feature store, model scores, generated content and the AI audit trail. "
          "Separate from ANALYTICS because its governance rules differ.",
    "GOVERNANCE": "Operational metadata: data dictionary, data quality rules and results, "
                  "lineage, pipeline run log, ingestion watermarks.",
}


def main() -> int:
    from local_warehouse.warehouse import shared
    con = shared()

    curated = {}
    for row in con.execute("""
        SELECT SCHEMA_NAME, TABLE_NAME, COLUMN_NAME, BUSINESS_DEFINITION, DATA_DOMAIN,
               CLASSIFICATION, IS_PII, PII_CATEGORY, DATA_OWNER, DATA_STEWARD,
               SOURCE_SYSTEM, RETENTION_MONTHS, MASKING_POLICY
        FROM ACME_EDP.GOVERNANCE.DATA_DICTIONARY""").fetchall():
        curated[(row[0], row[1], row[2])] = row

    # Ownership follows the domain of the entity, whichever layer it appears in.
    for (schema, table, _col), row in curated.items():
        TABLE_OWNER[(schema, table)] = row[8]
    for schema, table, owner in [
            ("RAW", "RAW_CRM_CUSTOMER", "VP Customer Experience"),
            ("RAW", "RAW_CRM_CUSTOMER_ADDRESS", "VP Customer Experience"),
            ("RAW", "RAW_CRM_CUSTOMER_CONTACT", "VP Customer Experience"),
            ("RAW", "RAW_CRM_INTERACTION", "VP Customer Experience"),
            ("RAW", "RAW_OMS_ORDER", "VP Commerce"),
            ("RAW", "RAW_OMS_ORDER_ITEM", "VP Commerce"),
            ("RAW", "RAW_PIM_PRODUCT", "VP Merchandising"),
            ("RAW", "RAW_SUP_CASE", "VP Customer Service"),
            ("RAW", "RAW_SUP_KNOWLEDGE_ARTICLE", "Customer Service Operations"),
            ("RAW", "RAW_LOY_ACCOUNT", "VP Loyalty"),
            ("RAW", "RAW_REJECTED_RECORDS", "Data Platform Owner"),
            ("STAGING", "STG_CUSTOMER", "VP Customer Experience"),
            ("STAGING", "STG_CUSTOMER_ADDRESS", "VP Customer Experience"),
            ("STAGING", "STG_CUSTOMER_CONTACT", "VP Customer Experience"),
            ("STAGING", "STG_CUSTOMER_INTERACTION", "VP Customer Experience"),
            ("STAGING", "STG_SALES_ORDER", "VP Commerce"),
            ("STAGING", "STG_SALES_ORDER_ITEM", "VP Commerce"),
            ("STAGING", "STG_PRODUCT", "VP Merchandising"),
            ("STAGING", "STG_SUPPORT_CASE", "VP Customer Service"),
            ("STAGING", "STG_LOYALTY_ACCOUNT", "VP Loyalty"),
    ]:
        TABLE_OWNER[(schema, table)] = owner

    schemas = ["RAW", "STAGING", "CORE", "ANALYTICS", "AI", "GOVERNANCE"]
    lines = [
        "# Data dictionary",
        "",
        "> Generated by `scripts/generate_data_dictionary.py` from the built warehouse.",
        "> Structure comes from the information schema; business definitions, ownership and",
        "> classification come from `GOVERNANCE.DATA_DICTIONARY`, which is curated by hand",
        "> because a machine cannot write a business definition.",
        "",
        f"Generated {datetime.now(UTC).strftime('%Y-%m-%d')}.",
        "",
        "## Conventions",
        "",
        "| Convention | Rule |",
        "|---|---|",
        "| Naming | `SCREAMING_SNAKE_CASE`; layer prefix only in RAW and STAGING |",
        "| Business key | The source's natural key, verbatim, suffixed `_BK` |",
        "| Surrogate key | `MD5` of the business key (+ effective date for SCD2), suffixed `_SK` |",
        "| Audit columns | `_SRC_SYSTEM`, `_SRC_FILE`, `_INGESTED_AT`, `_BATCH_ID`, "
        "`_CORRELATION_ID`, `_ROW_HASH`, `_LOADED_AT` |",
        "| Money | `NUMBER(18,2)` with an explicit currency column - never a bare float |",
        "| Time | `TIMESTAMP_NTZ`, UTC everywhere |",
        "| Reserved words | `ORDER` is reserved, so the order entity is `SALES_ORDER` |",
        "",
    ]

    total_columns = 0
    documented = 0
    for schema in schemas:
        tables = [r[0] for r in con.execute(
            "SELECT table_name FROM information_schema.tables "
            "WHERE table_schema = ? AND table_catalog = 'ACME_EDP' "
            "ORDER BY table_name", [schema]).fetchall()]
        if not tables:
            continue
        lines += [f"## {schema}", "", LAYER_NOTES.get(schema, ""), ""]
        for table in tables:
            cols = con.execute(
                "SELECT column_name, data_type, is_nullable FROM information_schema.columns "
                "WHERE table_schema = ? AND table_name = ? AND table_catalog = 'ACME_EDP' "
                "ORDER BY ordinal_position", [schema, table]).fetchall()
            try:
                count = con.execute(
                    f"SELECT COUNT(*) FROM ACME_EDP.{schema}.{table}").fetchone()[0]  # noqa: S608
            except Exception:                                  # noqa: BLE001
                count = "-"
            lines += [f"### `{schema}.{table}`", "", f"{count} rows in the sample build.", "",
                      "| Column | Type | Null | Class | PII | Definition | Owner |",
                      "|---|---|---|---|---|---|---|"]
            for name, dtype, nullable in cols:
                total_columns += 1
                c = curated.get((schema, table, name))
                if c:
                    documented += 1
                    definition = c[3]
                    classification = c[5]
                    pii = "yes" if c[6] else "no"
                    owner = c[8]
                else:
                    # Inferred, and marked as such. A dictionary that presents a
                    # guess with the same confidence as a curated entry is worse
                    # than one that admits the gap: the RAW copy of an e-mail
                    # address is exactly as sensitive as the CORE copy, and a
                    # reader must be able to tell which rows a human agreed.
                    definition = _inferred_definition(name)
                    classification, pii = _inferred_classification(name)
                    owner = f"{TABLE_OWNER.get((schema, table), '-')} *(inferred)*"
                lines.append(
                    f"| `{name}` | {dtype} | {'yes' if nullable == 'YES' else 'no'} | "
                    f"{classification} | {pii} | {definition} | {owner} |")
            lines.append("")

    lines += [
        "## Coverage",
        "",
        f"{documented} of {total_columns} columns carry a **curated** business definition, "
        "owner and classification, agreed with the domain owner. The rest are audit columns, "
        "structural keys, and RAW/STAGING copies whose classification is **inferred** from the "
        "column name and marked *(inferred)* in the tables above.",
        "",
        "The distinction matters. A dictionary that presents a guess with the same confidence "
        "as a curated entry is worse than one that admits the gap - and the RAW copy of an "
        "e-mail address is as sensitive as the CORE copy, whether or not anyone has "
        "written it down yet.",
        "",
        "Every column the platform classifies as PII names a masking policy; CI fails if one "
        "does not.",
    ]

    out = REPO / "docs" / "data-dictionary.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} - {total_columns} columns across {len(schemas)} schemas")
    return 0


# Column-name patterns that carry PII wherever they appear. Applied to the
# uncurated layers so that a RAW copy of an identifier is not presented as
# INTERNAL merely because nobody wrote it down.
PII_NAME_PATTERNS = {
    "EMAIL": ("RESTRICTED", "DIRECT_IDENTIFIER"),
    "PHONE": ("RESTRICTED", "DIRECT_IDENTIFIER"),
    "BIRTH_DATE": ("RESTRICTED", "QUASI_IDENTIFIER"),
    "DOB": ("RESTRICTED", "QUASI_IDENTIFIER"),
    "FIRST_NAME": ("CONFIDENTIAL", "DIRECT_IDENTIFIER"),
    "LAST_NAME": ("CONFIDENTIAL", "DIRECT_IDENTIFIER"),
    "FULL_NAME": ("CONFIDENTIAL", "DIRECT_IDENTIFIER"),
    "CONTACT_VALUE": ("RESTRICTED", "DIRECT_IDENTIFIER"),
    "LINE1": ("RESTRICTED", "DIRECT_IDENTIFIER"),
    "LINE2": ("RESTRICTED", "DIRECT_IDENTIFIER"),
    "POSTAL_CODE": ("RESTRICTED", "QUASI_IDENTIFIER"),
    "DESCRIPTION": ("RESTRICTED", "DIRECT_IDENTIFIER"),
    "RESOLUTION_NOTES": ("RESTRICTED", "DIRECT_IDENTIFIER"),
    "SRC_PAYLOAD": ("RESTRICTED", "DIRECT_IDENTIFIER"),
    "GENERATED_TEXT": ("CONFIDENTIAL", "NONE"),
    "GROUNDING_SNAPSHOT": ("CONFIDENTIAL", "NONE"),
}

TABLE_OWNER = {}


def _inferred_classification(name: str) -> tuple[str, str]:
    for pattern, (classification, _category) in PII_NAME_PATTERNS.items():
        if pattern in name.upper():
            return classification, "yes"
    return "INTERNAL", "no"


def _inferred_definition(name: str) -> str:
    if name.startswith("_"):
        return "Audit column - see the conventions above."
    if name.endswith("_SK"):
        return "Surrogate key: `MD5` of the business key."
    if name.endswith("_BK"):
        return "Business key from the source system."
    return "-"


if __name__ == "__main__":
    sys.exit(main())
