-- Statement executed by GET /customers/{customerId}/cases.
SELECT CASE_ID, CASE_TYPE, PRIORITY, SUBJECT, STATUS, CHANNEL, OPENED_AT,
       RESOLVED_AT, RESOLUTION_HOURS, CSAT_SCORE, REOPEN_COUNT, IS_SLA_BREACHED
FROM ACME_EDP.ANALYTICS.V_CUSTOMER_CASES_API
WHERE CUSTOMER_ID = ?
ORDER BY OPENED_AT DESC
LIMIT ?
